# Generated by Django 5.1.6 on 2025-02-27 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0004_alter_staff_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('totalbeds', models.IntegerField()),
                ('availablebeds', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='last_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='first_name',
            new_name='lastname',
        ),
    ]
